export const categoryData = {
  clothes: [
    { id: "c1", name: "Floral Summer Dress", rating: "4.5", price: "45.00", image: "/productes/clothes/black.jpg" },
    { id: "c2", name: "Silk Evening Blouse", rating: "4.2", price: "32.00", image: "/productes/clothes/dot.jpg"},
    { id: "c3", name: "Classic Denim Jacket", rating: "4.8", price: "55.00", image: "/productes/clothes/green.jpg"},
    { id: "c4", name: "White Summer Top", rating: "4.0", price: "25.00", image: "/productes/clothes/yellow.jpg" },
    { id: "c5", name: "Casual Linen Pants", rating: "4.4", price: "38.00", image: "/productes/clothes/shart.jpg" },
    { id: "c6", name: "Party Wear Gown", rating: "4.9", price: "120.00", image: "/productes/clothes/blue.jpg" },
    { id: "c7", name: "Knitted Sweater", rating: "4.1", price: "40.00", image: "/productes/clothes/gray.jpg" },
    { id: "c8", name: "Office Blazer", rating: "4.6", price: "85.00", image: "/productes/clothes/naseebo.jpg" },
    { id: "c9", name: "Boho Maxi Skirt", rating: "4.3", price: "50.00", image: "/productes/clothes/kurta.jpg" },
    { id: "c10", name: "Leather Mini Skirt", rating: "4.7", price: "65.00", image: "/productes/clothes/model.jpg" },
  ],
  wallets: [
    { id: "w1", name: "Leather Slim Wallet", rating: "4.2", price: "25.00", image: "/productes/wallets/v1.jpg" },
    { id: "w2", name: "Modern Card Holder", rating: "4.5", price: "15.00", image: "/productes/wallets/v2.jpg" },
    { id: "w3", name: "Bifold Classic", rating: "4.0", price: "30.00", image: "/productes/wallets/v3.jpg" },
    { id: "w4", name: "Zipper Purse", rating: "4.8", price: "40.00", image: "/productes/wallets/v4.jpg" },
    { id: "w5", name: "Designer Clutch", rating: "4.6", price: "95.00", image: "/productes/wallets/v5.jpg" },
    { id: "w6", name: "Vintage Pocket Wallet", rating: "4.1", price: "20.00", image: "/productes/wallets/v6.jpg" },
    { id: "w7", name: "Premium Suede Wallet", rating: "4.9", price: "55.00", image: "/productes/wallets/v7.jpg" },
    { id: "w8", name: "Minimalist Sleeve", rating: "4.3", price: "18.00", image: "/productes/wallets/v8.jpg" },
    { id: "w9", name: "Formal Brown Wallet", rating: "4.4", price: "35.00", image: "/productes/wallets/v9.jpg" },
    { id: "w10", name: "Carbon Fiber Wallet", rating: "4.7", price: "70.00", image: "/productes/wallets/v10.jpg" },
  ],
  watches: [
    { id: "wt1", name: "Gold Chronograph", rating: "4.9", price: "120.00", image: "/productes/watches/w1.jpg" },
    { id: "wt2", name: "Silver Minimalist", rating: "4.5", price: "95.00", image: "/productes/watches/w2.jpg" },
    { id: "wt3", name: "Black Smart Watch", rating: "4.7", price: "150.00", image: "/productes/watches/w3.jpg" },
    { id: "wt4", name: "Brown Leather Watch", rating: "4.3", price: "80.00", image: "/productes/watches/w4.jpg" },
    { id: "wt5", name: "Royal Blue Analog", rating: "4.8", price: "210.00", image: "/productes/watches/w11.jpg" },
    { id: "wt6", name: "Skeleton Luxury", rating: "4.6", price: "450.00", image: "/productes/watches/w6.jpg" },
    { id: "wt7", name: "Diving Master", rating: "4.9", price: "320.00", image: "/productes/watches/w7.jpg" },
    { id: "wt8", name: "Women's Rose Gold", rating: "4.4", price: "110.00", image: "/productes/watches/w8.jpg" },
    { id: "wt9", name: "Digital Sport", rating: "4.2", price: "45.00", image: "/productes/watches/w9.jpg" },
    { id: "wt10", name: "Titanium Tech", rating: "4.7", price: "180.00", image: "/productes/watches/w10.jpg" },
  ],
  bracelets: [
    { id: "b1", name: "Silver Chain Link", rating: "4.7", price: "15.00", image: "/productes/bracelets/b1.jpg" },
    { id: "b2", name: "Natural Pearl", rating: "4.6", price: "35.00", image: "/productes/bracelets/b2.jpg" },
    { id: "b3", name: "Leather Wrap", rating: "4.3", price: "12.00", image: "/productes/bracelets/b3.jpg" },
    { id: "b4", name: "Luxury Gold Cuff", rating: "4.9", price: "150.00", image: "/productes/bracelets/b4.jpg" },
    { id: "b5", name: "Boho Beads", rating: "4.1", price: "10.00", image: "/productes/bracelets/b11.jpg" },
    { id: "b6", name: "Crystal Charm", rating: "4.8", price: "60.00", image: "/productes/bracelets/b6.jpg" },
    { id: "b7", name: "Diamond Tennis", rating: "5.0", price: "999.00", image: "/productes/bracelets/b7.jpg" },
    { id: "b8", name: "Magnetic Therapy", rating: "4.0", price: "20.00", image: "/productes/bracelets/b8.jpg" },
    { id: "b9", name: "Handmade Thread", rating: "4.5", price: "8.00", image: "/productes/bracelets/b9.jpg" },
    { id: "b10", name: "Platinum Band", rating: "4.9", price: "400.00", image: "/productes/bracelets/b10.jpg" },
  ]
};

export const newArrivals = [
  { id: "na1", name: "Urban Tech Hoodie", rating: "4.9", price: "89.00", image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7" },
  { id: "na2", name: "Midnight Stealth Watch", rating: "4.8", price: "245.00", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30" },
  { id: "na3", name: "Desert Suede Boots", rating: "4.7", price: "120.00", image: "https://images.unsplash.com/photo-1520639889313-72727617307a" },
  { id: "na4", name: "Titanium Cuff Link", rating: "4.5", price: "45.00", image: "https://images.unsplash.com/photo-1611085211827-73d6024acc71" },
  { id: "na5", name: "Over-sized Street Tee", rating: "4.6", price: "35.00", image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a" },
  { id: "na6", name: "Carbon Fiber Bifold", rating: "4.9", price: "65.00", image: "https://images.unsplash.com/photo-1614179662397-885f9ad6bbfa" },
  { id: "na7", name: "Classic Aviators", rating: "4.4", price: "180.00", image: "https://images.unsplash.com/photo-1511499767350-a1590fdb7318" },
  { id: "na8", name: "Matte Black Bracelet", rating: "4.8", price: "25.00", image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a" },
];